import "~/styles/globals.css";
import "@meshsdk/react/styles.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { MeshProvider } from "~/components/providers/mesh-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <MeshProvider>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </MeshProvider>
      </body>
    </html>
  );
}
