import "~/styles/globals.css";
import "@meshsdk/react/styles.css";

import { type Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { MeshProvider } from "~/components/providers/mesh-provider";
import { AndamioAuthProvider } from "~/contexts/andamio-auth-context";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  weight: ["300", "400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={spaceGrotesk.variable}>
      <body>
        <MeshProvider>
          <AndamioAuthProvider>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </AndamioAuthProvider>
        </MeshProvider>
      </body>
    </html>
  );
}
